package com.example.banat_travel_app;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.widget.TextView;

public class ActivityPresentation extends AppCompatActivity // clasa in care se desfasoara prezentarea 'activitatii' selectate in activitatea 'Activities'
{

    private TextView location_name, location_description;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_presentation);
        setVariables();
        setLayoutXML();
    }

    private void setVariables() {
        location_name = findViewById(R.id.location_details_name);
        location_description = findViewById(R.id.location_details_description);
    }

    private void setLayoutXML() // in functie de 'activitate', setam si afisam pe ecran descrierea sa
    {
        Bundle extras = getIntent().getExtras();
        String description = "";
        if (extras != null) {
            location_name.setText(extras.getString("selected_location"));
            switch (location_name.getText().toString()) {
                case "The casino":
                    description = "  The casino is located in the central park and once communicated through two long corridors with painted vaults with the Hotel Traian and the Hotel Decebal. Built between 1862-1864, following the plans of the German architect Wilhelm von Doderer, it was designed as an amalgam of styles, with particularly rich exterior decorations that can be admired for the most part today. Designed as a place for recreation, the casino had a performance hall, a restaurant and a games room where roulette enthusiasts met.\n\n    If in the glory years it was the point of attraction for the aristocrats who came to the resort, in the years after the war it housed, as evidenced by the plaques left on the doors, the Performance Hall of the House of Culture and the History Museum 'Nicolae Cena'. Although today it is classified as an 'architectural monument', this beautiful building is deserted.";
                    break;
                case "The cast iron bridge":
                    description = "   The bridge was built at the same time as the Austrian Imperial Baths, between 1883 and 1886, and was intended for pedestrian traffic.\n\n  It has a width of 2.90 m and a length of 32 m, with an arched structure with two-joint lattice and vertical uprights made of cast iron clad with cast iron elements, and the bridge parapet is made of wrought iron with decorative elements.";
                    break;
                case "The cave of outlaws":
                    description = "   Visiting the Cave of Outlaws (also known as the Cave of Thieves) is an escape from the urban world.\n\n    At the end of the stairs, the main entrance awaits you, inviting you into a labyrinthine experience. As soon as you enter the darkness, the thought escapes you to the man in the cave. After deciphering the signs on its walls, you discover another crack in the mountain. Beyond it, the greatness of greenery and wildness.\n\n    You go back to look. You are in the place where once, the thieves of the Roman period hid their treasures here. Clearly, many have crossed its \"threshold\" if it has been inhabited since the Middle Paleolithic.\n\n    What other mysteries does this shelter hide in the rock?";
                    break;
                case "Decebal Hotel":
                    description = "   Hotel Decebal was built in 1865 and is one of the oldest in Herculane. Princes and kings crossed his threshold, but his fame was brought to him by a mysterious story, still unknown.\n\n   Local legend has it that a treasure was buried under the Decebal Hotel, and that it was guarded by a ghost.\n\n    The Decebal Hotel became world famous in 1897. Then, at the invitation of Emperor Frantz Joseph, the Emperor of Romania Carol I and King Alexander of Serbia are present.";
                    break;
                case "Diana thermal bath":
                    description = "   The thermal bath was built of brick in 1810 and in 1858 it was restored in its current form.\n\n    The roof has a terrace with a parapet, which has a statue of Hercules on one of the corners. In the years 2001-2002, the bathroom was rehabilitated and modernized, through the investment that had as object the Ferdinand Hotel. It has 9 individual cabins and a shared pool and is directly connected by a covered corridor to Hotel Ferdinand.";
                    break;
                case "Domogled-Valea Cernei National Park":
                    description = "   The natural area is located in the central-eastern part of Caraș-Severin County, the northwestern part of Gorj County and in the northeastern part of Mehedinți County and is to be crossed by the national road 66A, to connect Hunedoara and Caraș Severin counties.\n\n   When you miss Banat, remember that besides the beautiful cities you can visit there is a wonderful natural park, which hides one of the oldest reservations in the country: Mount Domogled Reservation. Over 1000 hectares of living nature, with many endemic species of special plants, including the Banat Black Pine, nature unaltered by the footsteps of people who explore its routes or animals in search of food.";
                    break;
                case "Goddess Diana's statue":
                    description = "   The statue of the goddess Diana is a historical monument located on the territory of Băile Herculane.";
                    break;
                case "Hercules square":
                    description = "   The architectural ensemble 'Hercules Square' bears the aura of a bygone era, being represented by monumental buildings in Baroque and Neoclassical style, built in the early nineteenth century, around the statue of Hercules.\n\n    The statue was erected in 1847, instead of a fountain built in 1826 of red marble and supplied with water from the Munk spring. Cast of metal for the cannon barrel, the statue was made in the workshop of Ramelmayer and Glantz in Vienna, being donated to the Baile Herculane resort by the heir archduke Carol, as a thank you for healing the soldiers who were treated here. One of the buildings of the architectural ensemble is the hotel 'Traian', built in 1869-1871 and renovated in 1969. The hotel is one of the architectural jewels, presenting unique ornaments both outside and inside.\n\n    The 'Hercules Square' spa architecture ensemble is on the list of historical monuments, thus consolidating the cultural potential of this resort.";
                    break;
                case "Mihai Eminescu's bust":
                    description = "   At Băile Herculane we meet the bust of Mihai Eminescu, made by the sculptor Oscar Han, author who modeled the poet's portrait in many variants, located in different places in the country: from the Putna monastery to Timişoara.\n\n   The statue from Băile Herculane seems to have been originally placed in front of the Romanian Casino and moved in 1948 in front of the Traian Hotel.";
                    break;
                case "Roman Hotel":
                    description = "   Surrounded by a forest overlooking the Cerna River, this quiet hotel is a 5-minute walk from the Cave of Outlaws and 6 km from Baile Herculane Train Station.\n\n   The simple rooms offer views of the river or the forest. Children up to the age of 9 enjoy free accommodation in an adult room.\n\n    The hotel offers access to an indoor thermal pool, a wellness center with geothermal baths and a fitness room. There is a relaxed restaurant and a bar. Parking is available, as well as breakfast (fees apply).";
                    break;
                case "The stone bridge":
                    description = "   The Stone Bridge with covered corridor was built in a curve in 1864, being one of the remarkable technical achievements of the resort in the 19th century.\n\n   Lithographs show the initial existence of a wooden bridge built in an angular shape since 1770, but floods and wars with the Turks caused the destruction of the wooden bridge. In 1864, the Stone Bridge was built, which connected the 'Franz Joseph' hotel with the Apollo, Hebe and Diana baths in Hercules Square, in the form in which it still exists today.\n\n   The stone bridge is one of the national heritage monuments in Băile Herculane.";
                    break;
                case "The train station":
                    description = "   The station building was inaugurated on May 20, 1878 and is a copy of Empress Maria Theresa's Vienna hunting lodge.\n\n    Located 16 km from Orşova, at the intersection of the E70 road with DN608D, the train station greets its visitors with the greeting of \"Welcome\" inscribed in the mosaic of the platform. Clean and quiet, despite the passing of the years, with benches sheltered from the heat of summer under the canopy of greenery, the old platform awaits the footsteps of travelers in the uninterrupted flow of time as once measured by the old Paul Garnier clock. Although the whole remains an important landmark of pre-war architecture, it is still visible that the passage of time has left deep traces, which although they can not overshadow the beauty of the elements that decorate the central pavilion, nevertheless, urgent measures must be taken to restore this true business card. resort. The beautiful multicolored mosaic dome is supported by columns, with the same message inscribed glorifying the holy waters of Hercules of Mehadia.";
                    break;
                case "The Banat sphinx":
                    description = "   The Banat Sphinx is one of the most spectacular anthropomorphic rocks in our country. Topleț is a small town located 3 km from Baile-Herculane. The sphinx is located on the Cerna Valley as it comes from Orșova to Herculane. More precisely on the European road E70, about 2 km after Topleț, on the right side. It is about 16 meters high and 8 meters wide.\n\n  In the past, the Banat Sphinx, as it is also called, could be seen quite easily from the street, but now due to the dense vegetation it is more hidden. However, you can reach the sphinx relatively easily and quickly if you follow the route that starts right from Topleț. Cross the concrete bridge over the river Cerna and advance along the gardens of the locals to the sphinx. I've only been here once, but whenever I drive around the area, I look for it.";
                    break;
                case "Berzasca commune":
                    description = "   Berzasca is the village of residence of the commune of the same name in Caraș-Severin County, Banat, Romania.\n\n   The relief consists of mountains, hills, terraces and meadows that run in steps from north to south. The mountainous relief is represented by the Carpathian border of the Locva and Almaj Mountains.\n\n   From the climatic point of view, the locality falls within the moderate temperate-continental area, with accentuated Mediterranean influences, with the concrete manifestation of two local microclimates, corresponding to the mountainous and depressional areas.\n\n    The vegetation on the territory is made up of deciduous forests, meadows and ruderal groups, being arranged in specific floors, conditioned by the natural environment, in which lithology varies and diversified relief (hill, mountain, terraces, meadows) and climate, generally warm -umed, have a determining role.";
                    break;
                case "Bigăr waterfall":
                    description = "   The Bigăr Waterfall in Romania is one of the many beauties that nature has made available to viewers.\n\n   The water is rich in limestone and flows into the Miniș River on a rocky threshold about 8 meters high, covered with moss, forming our famous waterfall. The water comes out from under a rock that is over 50 meters high. In winter, the icy icicles of the waterfall form a real Palace of Cloister.\n\n    Those who want to see more sights in the area and find out more interesting stories and legends pay a small fee. The water is very clean and drinkable.\n\n    You go up to the spring on a rocky path, then you reach a wooden bridge over the river and you reach the cave.\n\n   The waterfall is extremely beautiful, as well as the other lenses that you can visit in the area, but do not go on the road with the hope that you will see it as it is presented in most images circulating on the internet understanding that the photos have been \"easily\" processed.";
                    break;
                case "Coronini commune":
                    description = "   The commune is the newest Romanian colony in the Danube gorge. Its history is swirling like the waters of a river on the brink of a storm.\n\n   This corner of Romania has always been one of incomparable beauty. On the one hand, the quiet glows of the Danube, and on the other hand the relaxing green of the hills and mountains with nearby forests. Beyond the fact that this area has been blessed with so many beauties, the place presents opportunities for profitable tourist businesses.\n\n   Near Coronini, the Danube dug its way through Mesozoic limestone. In the limestone wall on the Romanian shore, the mouth of a 'Gaura cu Musca' cave opens. This cave has travertine dams, behind which accumulate stone milk, odontolites and stalactites.";
                    break;
                case "The devil's lake":
                    description = "   It is the largest karst lake in Romania, formed by the collapse of the ceiling of a cave. It is 13m deep, 20m in diameter and a fabulous color at the right time of day, for a short period of time, when the sun's rays reach it through the thicket of the beech forest.\n\n   As a legend fits any objective, the name of the lake comes from a remnant between a devil and a goatherd, a bet that the devil lost and despite throwing himself into the water that swallowed him.\n\n   The shepherd on the shore of the lake is shown the devil leaping from a hole. The devil made him roast the fish he was holding in his hand, without getting caught in the fire. The pastor cut off a goat's head and asked the devil to burn it instead, so that his head would not grin in the fire.\n\n   The shepherd passed the fish along the length in a spike and thus managed to roast it without entangling it, instead, no matter how much the devil struggled with the goat's head, the flesh gathered from the heat of the fire revealed his teeth, so he failed to He wipes his grin, losing his bet.\n\n   It is said that the lake is bottomless, due to the underground tunnels, and that whoever dares to bathe in its waters, never returns to the surface.";
                    break;
                case "Eftimie Murgu water mills":
                    description = "   In the west of Romania is the land of water mills. The locals boast that the flour from these mills has a unique taste.\n\n   One of the fascinating places in Romania is the mill complex in Banat, Caraş-Severin County. It is about the 22 water mills on the Rudăriei Valley, which are still working. Thus, tourists who arrive in the commune of Eftimie Murgu can see how the grains are ground as in the time of the Dacians and can receive on departure also ground flour from the villagers. Therefore, the water mills from Rudăria defy not only time, but even modern technology.";
                    break;
                case "Moldova Nouă town":
                    description = "   Moldova Nouă is a city in Caras-Severin County, Banat, Romania, consisting of the component localities Măcești, Moldova Nouă (residence), Moldova Veche and Moldovița. It has a population of over 13,000 inhabitants. It is one of the most important cities in the county.\n\n    It was first attested around 1600. Since 1956 it has been a city.";
                    break;
                case "Ochiul Beiului lake":
                    description = "   At the shelter of the Anina Mountains is one of the most charming lakes in Romania. Lake Ochiul Beiului awaits visitors with its clear water of an unreal blue.\n\n   Although the route to this natural wonder is difficult, those who dare to cross it are immediately enchanted by this almost mystical landscape.\n\n   At the base of the formation of this unique lake are some legends that those in the area keep with sanctity for the curious who step on their doorstep.\n\n   One of the legends says that a beautiful girl from these places was kidnapped and dishonored by a young Turk, drunk in the Ottoman Empire. However, the girl managed to escape from the young man's hands and took her days. The drunkard would have wept so bitterly that his tears turned into a lake. That's how the Eye of the Bee would have been born.";
                    break;
                case "Comarnic cave":
                    description = "   Comarnic Cave is in the top of the most important such objectives in the Banat area. With a length of about 6203 meters and a level difference of about 100 meters it is developed on three levels. It attracts hundreds of tourists through the attractive appearance of the existing underground formations.\n\n   The cave is not part of the electrified cave circuit, but the guide provides people with light sources and helmets for everyone's safety. This makes the cave even more impressive among tourists through the speleological authenticity offered.\n\n   The cave was discovered in 1896, and no details are known about its discoverer. Because access is very easy, the cave has been among the most studied over time from a scientific point of view.";
                    break;
                case "Oravița-Anina historical railway":
                    description = "   The Oravița – Anina railway was inaugurated on December 15, 1863, being the first mountain railway (and the fourth built) on the current territory of Romania.\n\n   Its construction began in 1861 and was a difficult engineering work because it was located in a mountainous region (western part of the Banat Mountains), difficult to access by climbing the 33.4 km of the route, 339 m, having no less than 14 tunnels with a total length of 2.1 km and 9 viaducts.\n\n    The route starts from Oravița (city located at 220 m average altitude) then climbs on the plateau of the Semenic Mountains massif, following a route on which there is no other road. Due to the small radii of curvature, some even only 104 m, and the large ramps, the line is very similar to the famous Semmering railway.";
                    break;
                case "Reșița's emblem":
                    description = "   An emblem of the Reșița's industry still reigns today, imposing, above the Civic Center, still arousing a series of nostalgia, which catch a cyclical voice, usually around the anniversaries with significance for the life of the city.";
                    break;
                case "Secu lake":
                    description = "   The Secu dam was built in 1963, being designed, in particular, to supply water to the city of Resita, but also to protect it in case of floods. In order for this dam to be built, the village of Secu was swallowed by the waters, as well as a railway that was used to transport wood from the mountains. Thus, the approximately 20 households, plus a small wooden church, were flooded, the locals being forced to move to a neighboring village.\n\n   The locals say that, over time, at least strange things happened at Secu Lake, and that is why they consider it cursed. Thus, the villagers say that sometimes, for those who pass by boat over the village, the waters of the lake suddenly become transparent, and under the waves the forester's house and the wooden church can be seen. Other people say that in this lake live sea monsters that attack people and that they saw huge snakes in Secu.";
                    break;
                case "Steam locomotives museum":
                    description = "   The museum was established in 1972. It currently exhibits a number of 16 locomotives from different centuries, of which 14 were manufactured in Resita, and two elsewhere.\n\n   The most important piece is the 'Resicza' locomotive, which greets visitors at the entrance to the park. It is part of a series of 3 locomotives built here in 1872 after a prototype built in Vienna, destined for the Reșița-Secu mountain route. 'Resicza' is also the oldest locomotive in the park, being manufactured in 1872, and the newest is the narrow gauge locomotive CFR 764.001 from 1958.\n\n   The Museum of Steam Locomotives from Reșița is a unique collection that illustrates the progress of almost a century of walking on its own and including locomotives representative of the evolution of this industry. The era of building steam locomotives ended in 1964, when the construction of diesel and later electric locomotives began.";
                    break;
                case "The Caraș quays":
                    description = "   The Caraș Quays is one of the longest and wildest gorges in Romania and represents two sectors of gorges separated by Lunca Prolazului, a place where the slopes retreated to make way for the few houses and households on the banks of the Caraș River.\n\n   These gorges form one of the most spectacular landscapes in southwestern Romania, having the shape of canyons that include countless species of plants and animals, along with beech forests, which, especially in autumn, is a wonderful landscape.\n\n    The flora and fauna are as varied as they are unusual. Predatory birds can be found, such as the mountain eagle, the serpent and the peregrine falcon, but also the viper and the hazel snake or some species of bats. The wolf, the marten, the lynx, the deer, the Carpathian bear can get in your way, which are just some of the wildlife we encounter here.\n\n    The paths are narrow and the route is marked with a blue triangle.";
                    break;
                case "Semenic mountain":
                    description = "   Banat has a huge tourist potential. From the beaches on the banks of the Danube, to the breathtaking Clisura to the high mountains and spas or lakes with crystal clear water, Banatul Montan offers you everything.\n\n    The climate is mild, so bearable for children. In winter the temperatures are between -25 degrees Celsius and +6 degrees Celsius, and in summer, between +10 degrees Celsius and +25 degrees Celsius.\n\n   Semenic is one of the few places in the country where the snow persists even six months a year, during which tourists can ski at will, at acceptable prices. Also in the area, but in Văliug, was arranged the longest ski slope in the country, 5.8 kilometers, and another, 800 meters, equipped with night and 'artificial' snow cannons, we find in the description of the resort from a tourism site.";
                    break;
                case "Trei Ape area":
                    description = "   In the heart of the Semenic Mountains is a place full of wonderful landscapes in any season, an oasis of peace and relaxation. It is about the Trei Ape resort, located in the locality of the same name, in Caraş-Severin county, 37 kilometers from Reșița, where those who cross its threshold will surely enjoy the fresh mountain air.\n\n   The resort is located right next to Lake Trei Ape, the highest accumulation lake in the Semenic massif, considered by tourists a place of story in any season. The name Trei Ape, given to both the resort and the lake that formed in this area, comes from the three streams that come from the mountains, Brebu, Grădiște and Semenic, which meet here to give birth to the river Timiș.\n\n   The Three Waters resort is appreciated by winter sports lovers, and that's because there are ski slopes here. Moreover, tourists curious to exploit the surroundings can start on very well marked routes to the Anina or Semenic mountains, but also to the nearby tourist villages, such as Gărâna or Brebu Nou. Such hikes can also be done in winter.";
                    break;
                case "Văliug commune":
                    description = "   The Semenic mountains are known as the pearl of the Banat mountains. The highest peaks are Piatra Goznei Peak (1447m), Semenic Peak (1445m) and Nemanu Peak (1122m).\n\n    Located at the foot of Mount Semenic, at an altitude of 600m, Lake Valiug is preferred by many tourists who love water sports or fishing. But there are just as many who come to the area only for relaxation, beach and outdoor walks.";
                    break;
                case "Danube's boilers gorge":
                    description = "   The Danube is one of the spectacular rivers of Europe, and at its entrance in Romania, visitors have a truly fascinating spectacle.\n\n   The Big Boilers, with a length of about 4 km, are a spectacle of nature, and the curious can find out other interesting things.\n\n   At the base of the limestone wall that flanks this part of the Cazanelor Mari there are two cavities: Gura Ponicovei and Veterani caves.\n\n    Instead, Cazanele Mici stretches over a length of about 3 km, being positioned between the Ciucarul Mic (Romania) and Mali Strbac (Serbia) massifs.\n\n   Near Mraconia Bay, you can see, dug into the rock, the face of Decebalus, the statue of Decebalus having impressive dimensions 55 m high and 25 m wide. It is the largest sculpture in all of Europe and was completed in 2004, after 10 years of work, executed by 12 alpine sculptors.";
                    break;
                case "Mraconia monastery":
                    description = "   Tourists arriving in the Small Boilers of the Danube, near Orșova, can admire a truly spectacular appearance. It is about the Mraconia Monastery, also called the 'underwater monastery', located next to the huge statue of Decebalus, the largest stone sculpture in Europe.\n\n   In an impressive place where the Carpathian mountains meet the Danube, on the border between Romania and Serbia, a wonder of nature was formed. The so-called 'La Cazane', which is said to be the most spectacular part of the Danube. Among the unique tourist attractions in this area are the statue of Decebalus, but also the Mraconia Monastery, 'the place under God's heaven'.\n\n    The monastery is located in a fairytale land, at a distance of about 12 kilometers from Orșova, between the villages of Dubova and Ieșelnița, and it cannot escape the eyes of curious tourists who arrive at Cazanele Mici. 'Born and killed several times, the monastery appears today, beyond death, as a certainty of faith, hope of the Resurrection and foundation of love,' he writes on the window at the entrance to the monastery.";
                    break;
                case "Ponicova cave":
                    description = "   The Ponicova Cave is also known as the Bat Cave, being the largest formation of its kind in the Danube Gorge.\n\n   The name 'Cave of Bats' was given to it because whole colonies of bats live here in the Gallery that bears their name. Due to them on the ground you can see many guano mounds from large bats. This cave was dug in the limestone wall of the left slope of the Danube, more precisely in the area of Cazanele Mari, Ciucaru Mare and is located a short distance from the Dubova lake in Mehedinți county. Its galleries total about 1,660 meters along Ciucaru Mare and then out into the Danube. We must know that the galleries were partially flooded after the creation of the dam lake.\n\n   The cave consists of several galleries that join and are located on two floors. From the part leading to Ponicova you enter the gallery called Ogașul Ponicova, or on a narrower part you reach directly the Galeria Liliecilor. This room is over 100 meters long, 30 meters high and about 60 meters wide. On the floor here you can see various blocks of collapses, concretions and pits.";
                    break;
                case "The rock sculpture of Decebalus":
                    description = "   There is no man who reaches the area of the Danube Boilers and does not want to see the Face of Decebalus in the rock. The tallest mountain sculpture in Europe still attracts tens of thousands of tourists today. People come, take pictures and leave. Little do I know, however, that the goal is far from over.\n\n    The largest stone sculpture in Europe was the wish that became a reality of one of the richest people after the Revolution - Iosif Constantin Drăgan. With a life lived a few decades away from the country, Drăgan had an estimated fortune in 2006 of 1.3 billion dollars. The sculpture cost him no less than a million dollars. Under the head of Decebalus was inscribed in the rock the inscription 'DECEBALUS REX - DRĂGAN FECIT' ('King Decebalus - made by Drăgan').";
                    break;
                case "Tricule fortress":
                    description = "   A tourist attraction in the west of the country amazed an entire world. It is about the mysterious Tricule Fortress, located on the banks of the Danube, in Mehedinţi County, about which few people know that it was included, two years ago, in a top of the most spectacular sunken buildings in the world. The fortress is partially submerged under the river and is one of the most important tourist attractions in the Danube Boilers.\n\n   It is located on national road 57, four kilometers downstream of Şviniţa, on the left bank of the Danube. The fortress is also known as Tri-kule or Triculi, and its name comes from the fact that it had three towers arranged in the corners of a hypothetical triangle. At this moment, tourists arriving in Mehedinţi County can admire only two of them, the third being swallowed by the Danube water almost a hundred years ago. However, during periods of drought, its base can also be seen, when the water level is low.\n\n    The three culverts were built in the 15th century by Petru Petrovici in order to stop the Ottoman expansion to the west.\n\n    The fortress was built of raw stone, and the walls of the towers are 1.4 meters thick. They had three levels inside, used for food storage, surveillance and defense of the area. The towers that can be seen at this moment are ten and eleven meters high, respectively, the river segment of one of the towers collapsed due to the fault of the treasure hunters.\n\n   Currently, the foundation of the Tricule Fortress is deeply eroded. This is how the walls of the towers become more and more fragile, the only solution being their consolidation. This is why the visiting conditions are precarious.";
                    break;
                case "Veterani cave":
                    description = "   Famous both for its legend and for its more unusual and somewhat adventurous access - made only on water, the Veterani Cave has its name after the one who was Ianovici's aide, the commander of the Austrian army stationed at Caransebes and who fortified the cave at end of the seventeenth century.\n\n    The Veterani Cave has always been in the attention of treasure hunters around the world, who claim that the famous silver treasure of Empress Maria Theresa belonging to the Austro-Hungarian Empire or the treasures of the Serbian Tsar Obrenovich were hidden in a cave with rocks. It is said that in Cuza's time, Obranovici, the prince of Serbia, who had quarreled with his brother, Mihai, crossed into Romania with 80 horses carrying bags of gold. All Serbian soldiers who brought this treasure, after it was hidden, were killed. It is also said that the only indication of where the treasure is, is a stone on which a snake is inlaid.\n\n   There is also talk of the treasures of the Basarab people, of which the abbot Nicodemus, himself a descendant of the family, would have taken part to build the monastery at Tismana, and the rest of the treasure would have hidden him in a cave in the Danube Gorge.\n\n    The legends of the place say that, in the cave, the Dacians had for a long time an altar where they worshiped Zamolxis and in whose honor they made sacrifices, thus explaining the bones of birds and animals discovered by archaeologists in several places dug in stone.";
                    break;
                case "Cruise on Danube":
                    description = "   On route Orsova - Cazanele Mari you can admire the most beautiful landscapes created by the Danube in Romania. Besides the steep cliffs, caves created by water, bays and other natural landscapes ... admire also the countless historical sites such as Tabula Traiana, Mraconia Monastery, and grandiose sculpture 'The Statue of Decebalus.'";
                    break;
                case "Clisura Dunării":
                    description = "  Clisura Dunării is a geographical region located along the northern bank of the Danube, in the south of Banat. The region, which is located on the territories of Caraş-Severin and Mehedinți counties, is limited by the river Nera to the northwest and by the Danube Boilers to the east.\n\n   Geographically spectacular, the area is also very important in terms of biodiversity, with a large number of nature reserves, currently included in the Iron Gates Natural Park.";
                    break;
                case "Iron Gates I":
                    description = "   The Iron Gates I hydropower system was inaugurated on May 16, 1972, and construction began on September 7, 1964. The system had a capacity of 1050 MW in both the Romanian and Yugoslav parts, being the largest hydropower plant on the Danube River and one of the largest hydroelectric constructions in Europe.\n\n   With a volume of over 2,200 million cubic meters, its reservoir stretches from the dam to the confluence with the river Tisza. The lake mainly includes the Danube Gorge area, the largest gorge in Europe, between Baziaş and Orşova.\n\n    At the same time, the total length of the dam is 1,278 meters, of which the overflow dam is 441 meters, the nominal water fall being 27.17 meters.";
                    break;
                case "Saint Anne Monastery":
                    description = "   A monastery is always an ideal place where you charge with love, calm your bewildered soul and connect with the divinity. All the more so these things happen at the Monastery of St. Anne in Orsova which has the Danube close and a story about faith, gratitude and love.\n\n   St. Anne Monastery is an oasis of peace in the middle of nature, it is a small universe protected by trees, protected from the surrounding world. In the distance, the Danube shines incessantly, inviting you to a peaceful stay, a stay in which the essential communication is from the soul to the soul, the words no longer having a purpose.";
                    break;
                case "Vodița Monastery":
                    description = "   On European Road 70 between the municipalities of Drobeta-Turnu Severin and Orşova, tourists arriving in the area can make a stop at the Vodiţa monastery in Mehedinţi county, which is the oldest documented voivodship and also the first monastic settlement in our country administered autonomously according to church rules established by St. Basil the Great.\n\n   It was built between 1370 and 1372 by Saint Nicodemus at the expense of the voivode Vladislav I. Since its establishment, it has been endowed by the ruler with valuable church odors, money and other income.\n\n   The expansion of the Ottoman Empire at the end of the 15th century for the conquest of the peoples of Europe directly influenced the existence of the Vodita Monastery. Thus, after the occupation of the fortress of Severin by the Turkish armies led by Baliberg in 1524, all the old estates of the foundation of Saint Nicodemus are confirmed, one by one, to the Tismana Monastery.\n\n    Following the Austro-Turkish war ended with the peace of Passarovitz in 1718, the Vodita Monastery will experience a new period of decline. It will be mentioned only on the map drawn up in 1720 by Samuelis Köleseri.";
                    break;
                case "Buziaș Colonnade":
                    description = "   The colonnade from Buziaş, built in 1875, at the order of Emperor Franz Joseph, was rehabilitated with over 5 million lei, money from the local budget. The Austrian emperor Franz Joseph and his wife, Sisi, used to come to Buziaş for mineral water cures.\n\n   The colonnade from Buziaş was built of wood, in Byzantine style, and surrounds the park of the resort, having a total of 500 meters.\n\n    The colonnade is the longest of its kind, surpassing those of Karlovy Vary (Czech Republic) and Baden-Baden (Germany), with which it resembles.";
                    break;
                case "The Buziaș Park":
                    description = "   The Dendrological Park from the Buziaș resort occupies an area of 20 ha, where many species of trees can be found, of which the most widespread is the plane tree.\n\n   In the past, many squirrels lived in the Dendrological Park, which had become mascots of the Park, but now they can be seen less and less. In recent years, the City Hall together with the Association for the Development of the Buziaș Area are making efforts to repopulate the park with squirrels and organize the Squirrels Festival annually.";
                    break;
                case "The Cramele Recaș winery":
                    description = "   The Cramele Recaș brand is proud of assortments of white, red, rosé and sparkling wine repeatedly awarded at national and international competitions and appreciated by the public in Romania and abroad.\n\n   The assortments satisfy the preferences of any type of consumer. The wines Schwaben Wein, La Putere, Huniade Castle, The Rooster of the Living, Solo Quinta, Sole, Selene, Ambrozy Mansion, Muse and Cuvee Uberland are a testament to tradition, innovation, passion and quality. The first historical records about the Recaş vineyards date back to 1447. The company was founded in 1991 out of the desire to carry on the cultivation of vines using modern equipment for dry, semi-dry, semi-sweet and sweet wines, but also a barricade line for superior wines.\n\n   Recaş wineries use the best production methods to preserve the best possible grape flavor and to offer the public the best quality products every year.";
                    break;
                case "The Baroque Orthodox Cathedral":
                    description = "   The church is one of the most imposing baroque buildings in Banat. It was built between 1759-1766, founded by the great Gavril Gurean, and was declared a historical monument.\n\n   The roof is semicircular, wrapped in copper foil. The bulb of the towers is in neo-baroque style. The doors are real portals, with a height of 3.8 m. The floor is paved with kelheim tiles.";
                    break;
                case "The city of Lugoj":
                    description = "   Lugoj was the center of a Romanian district that maintained its autonomy through the privileges and diplomas of the Hungarian kings until the 16th century.\n\n   Lugoj was once a strongly fortified settlement, having a greater importance than today. The first documentary attestation of the city of Lugoj appears towards the end of the 13th century, in a document preserved in the archives of Budapest, which shows that the king of Hungary, Ladislaus IV (1272 - 1290) stopped with his army at Lugoj.\n\n   A diploma dated August 22, 1376, signed by the King of Hungary Sigismund of Luxembourg, shows that the fortress of Lugoj was donated to the great feudal lords Ladislaus and Stephen Losonczy. At the end of the 14th century, especially after the battle of Nicopolis (1396), the Turks often crossed the Danube, invading Banat, reaching the parts of Lugoj. During the great anti-Ottoman campaigns, Ioan Huniade, when he was commissioned by Timiș (1440), took measures to organize the city's defense system, strengthening the fortress with ditches, ramparts and palisade.\n\n    In January 1601, Mihai Viteazul passed through Banat with his suite and stopped in Lugoj, at the Post Office Inn, on his way to Vienna.";
                    break;
                case "The Surduc lake":
                    description = "   The Surduc accumulation lake, the largest in Timiş County, was formed after the construction of the dam in the Poiana Ruscă Mountains area began in 1972. In five years, the lake, with an area of 460 hectares and a depth of up to 20 meters , reached 25 million cubic meters of water, about half the capacity at which it was designed. The lake, which largely supplies drinking water to Timisoara and the surrounding area, has become in the last two decades one of the most famous tourist attractions in the county.\n\n    Although it is a relatively new artificial lake, it also has its legend, as it suits any place that wants to attract as many tourists as possible. Several spirits would live in the depths of the lake, and according to local fishermen, who are ready to swear that they saw the sight with their own eyes, a four-eyed monster, similar to the one from Loch Ness, makes its head at the bottom of the lake. water only on full moon nights.";
                    break;
                case "The I.C.Drăgan square":
                    description = "   The square is positioned between the Iron Bridge and the City Hall. It is named after the businessman and philanthropist Josif Constantin Drăgan.\n\n   The square is guarded by constructions with a special historical importance, buildings that testify without words about the troubled history of Lugoj.";
                    break;
                case "Theresia Bastion":
                    description = "   The Theresia Bastion, named after the Austrian Empress Maria Theresa, is the largest preserved piece of defensive wall of the Austrian-Hungarian fortress of Timișoara. It covers about 1.7 hectares of the city center. It was built between 1732 and 1734. Today it is used as a passage, but it also houses commercial spaces, restaurants, bars, a disco and a library, and two permanent exhibitions of the Museum of Banat, the Information and Communications Technology 'Violin – a passion for life', and the Ethnography Museum Village.\n\n   After the conquest of Timișoara by the Habsburgs in 1716, it was realized that the old fortifications could not cope with new fighting techniques, therefore it was decided to rebuild the whole city in Pagan style (a fortress-stronghold of a stellar shape). It had an area larger than the Ottoman medieval fortress. The city was surrounded by three stellar belts that could be filled with water. Access was via three gates: of Vienna, Petrovaradin and Transylvania (completely demolished in 1891). The nine bastions of the fortress were named after kings and queens or generals. In the second half of the 19th century, the majority of the city walls was demolished to make room for the rapidly expanding city.";
                    break;
                case "Timișoreana beer factory":
                    description = "   The Timişoreana beer factory is located in the old Timişoara neighborhood Fabric, near Traian Square, the central point of interest of this neighborhood. Although the factory buildings have been renovated, they retain the architectural style of the eighteenth century.\n\n    Next to the factory there is a brewery with a terrace, which has the air of an old inn, where visitors can taste locally produced beers. The factory was established in 1718, a year of grace in the history of Timisoara, when the city was liberated from Ottoman rule by Austrian armies led by Prince Eugene of Savoy. After the conquest of the fortress, he ordered the construction of a brewery, for very practical reasons: lack of drinking water, there were few wells in the city, but also the fact that Austrian soldiers being accustomed to beer had difficulty consuming water from the swampy plain of Timisoara.\n\n   During its existence, the Timişoreana factory used many technological innovations, which were a first in the production of beer in Romania at the time of their introduction. Thus, in 1920, the first beer filter in the country was introduced in the Timişoara factory. a beneficial effect on the freshness of the beer and its preservation for a longer time. Also, in 1962, the old water filter made of gravel was replaced, which filtered the water brought from the Bega river through an underground canal, with a modern water treatment plant. At the time, it was the second semi-automated production unit in the world. In 2001, the factory was acquired by SABMiller - Ursus Breweries, which undertook an extensive modernization investment process.";
                    break;
                case "The Bega Canal":
                    description = "   The history of the Bega Canal begins in 1728 when Count Claudius Mercy ordered the digging of a canal to help rehabilitate the floodplains around Timisoara. Then the sewerage of the Bega river starts upstream from Timișoara, up to Făget. Four years later, in 1732, the first vessel to the Pancevo ran on the new canal. Between 1735 and 1754, a new variant was built, further south, between Timișoara and Klekk. The old canal is abandoned because of the sand thresholds that made it impassable, especially in summer, when the water level was low. The new route is much straighter and favorable to navigation, but it depends a lot on the water level whose flow fluctuates over the course of a year.\n\n    The work started by Mercy is also continued by the engineer Maximilian Fremaut. It continues the sewerage intervening with dams to regulate the course of Beghe. As a result, Timișoara benefits enormously from the reduction of the risk of floods, but especially from the drying of the swamps in the surroundings. In 1744 an imperial order was issued by which all communes along the Bega canal were obliged to maintain the banks and dams, and to help regularize the canal.";
                    break;
                case "Millennium Roman Catholic Church":
                    description = "   The largest Roman Catholic church in Timisoara, the Millennium Church, is the place of worship visited by tourists and Christians from all over the world.\n\n   As you walk into the church in the old Fabric district of Timișoara, your soul calms down and your worries are forgotten. Here, prayers are raised in heaven in several foreign languages and this is also the place where pilgrims, tourists and believers come from abroad.\n\n   The multiculturalism of the area was also transposed in the holy services held in the beautiful place of worship. Here, the message of the Lord is preached, since the past, in several foreign languages. Here, the holy services are officiated in Romanian, Hungarian, German and Italian.";
                    break;
                case "Huniade Castle":
                    description = "   Huniade Castle is a historical monument and the oldest building in Timișoara, built between 1308–1315 by Carol Robert de Anjou and rebuilt after the earthquake of 1443 by Ioan de Hunedoara. The medieval castle was destroyed during the siege of Timisoara in 1849 and restored to its current form in 1856. Today it houses the Banat Museum.\n\n   In the context of the political turmoil in the Kingdom of Hungary in the 14th century, King Carol Robert of Anjou decided, following a visit in 1307, to temporarily establish his residence in Timișoara. It was thus necessary to build a castle to meet the needs of the king. The construction was probably made by Italian builders and most likely completed in 1315, because in 1316 the king was already settled in his new castle. He lived here for almost 8 years. The building developed around a quadrangular courtyard with cylindrical corner towers. Being located on an island, it was connected to the city of Timișoara, also fortified by the same king, through a drawbridge. He experienced major restorations during the Pippo Spano committee.\n\n   Between 1441 and 1456, the count of Timișoara was Ioan de Hunedoara. He established his residence here and ordered the construction of a new castle, on the ruins of the old royal palace-castle, severely damaged by an earthquake. A contribution to its construction was made by the Italian architect Paolo Santini de Duccio, who was in the service of Iancu de Hunedoara at that time. Both the castle and the fortifications of the city were equipped with semicircular towers adapted to artillery.";
                    break;
                case "The Metropolitan Cathedral":
                    description = "   The Metropolitan Cathedral of Timișoara is the largest religious building in Timișoara, the cathedral of the Metropolitan Church of Banat, dedicated to the 'Three Hierarchs'. It was built between 1936 and 1941 and is a symbol of the city. It is currently the tallest church in Romania (90.5 m) and the tallest Orthodox church in the world outside of Russia.\n\n   The history of the building is closely linked to the year 1919 when, on July 28, Banat joins Romania. The new Romanian administration resumes the broken thread of Orthodoxy in 1717 and takes a series of measures to encourage Orthodoxy, disadvantaged by the Austrian administration, favorable to the Catholic religion. Thus, the old parish of Cetate was re-established in 1926, then the Diocese of Timișoara in 1939, elevated to the rank of archdiocese, and in 1947 the Metropolitanate of Banat was created.\n\n   The architectural style of the cathedral is both unique and unusual for an Orthodox place of worship of this size. It combines the Romanian religious tradition with the Moldavian and Byzantine architecture. The style, with niches under eaves, with starry vaults inside, with discs lacquered in a multitude of colors, can be found in monasteries such as Cozia or Prislop, typical of the fourteenth century.";
                    break;
                case "The Dome":
                    description = "   St. George's Cathedral in Timisoara or the Roman Catholic Cathedral is the cathedral of the Roman Catholic Diocese of Timisoara and one of the emblematic monuments of the city.\n\n    The construction lasted over 2 decades, in 2 stages: 1736-1751 and 1755-1774. The monument is made in Baroque brick style and has stone and stucco decorations. The towers have a low height, determined by the proximity of the fortress wall. The interior is rich and sumptuous, highlighting the 9 altars decorated in Baroque and Rococo style, sculpted by the Viennese Johan Müller, adorned with old icons, the organ built in 1908 by Leopold Wegenstein, and oak doors decorated with pure nickel grilles. The Roman Catholic Cathedral (Roman Catholic Cathedral) is considered to be the most unitary and representative baroque construction of Timisoara and one of the most valuable in Banat.\n\n   Currently, liturgies in Hungarian, German and Romanian are held regularly in the Dom. Due to the special acoustics, organ concerts are also held here.";
                    break;
                case "The Botanical park":
                    description = "   The Botanical Park of Timișoara, also called by the locals the Botanical Garden, is designed as a dendrological park and was established between 1986–1990 by the architect Silvia Grumeza. It is located in the immediate vicinity of the former fortress and currently contains 218 species of plants.\n\n    The architect Silvia Grumeza developed the first plan of this project in 1966. Between 1986 and 1990, more than 1,650 species of plants of various origins were planted: parks in the country, private collections and international seed exchanges. In 1995 it was first declared a scientific reservation, in order to protect the local and exotic flora.";
                    break;
                case "The Roses park":
                    description = "   The park was established in 1891, together with the Children's Park, on the occasion of the Universal Exhibition (industrial, commercial and agricultural), when floral arrangements were made here by gardeners Wilhelm Mühle, Franz Niemetz and Beno Agatsy. The flowers were admired by Franz Joseph, who visited the exhibition. The landscaping of the park began in 1929 by landscape architects Árpád Mühle, son of Wilhelm Mühle, and Mihai Demetrovici, head of the horticultural service at that time. The park was decorated in English style, with alleys, canopies and rose bushes. In the interwar period the name of the park was Rosarium and here there were over 1200 varieties of roses, labeled. Also during this period, the open-air theater was arranged.\n\n    In 1944 the park was destroyed by bombing. After the Second World War, the park was rebuilt, with various outdoor shows. Also in the park there is a sports base, arranged in winter as an ice rink, and in summer as a tennis court.\n\n   In 2012 the park was redeveloped. Immediately next to the main entrance, from Academician Alexandru Borza Street, are the busts of Wilhelm Mühle (1844–1908), unveiled on August 2, 2013 and Árpád Mühle (1870–1930), unveiled on August 1, 2014.";
                    break;
                case "The Liberty square":
                    description = "   The Liberty Square (initially Paradeplatz, 'Parade Square', then Prinz Eugen Platz, 'Prince Eugene Square') is a historic square in Timișoara.\n\n   In 1848, with the outbreak of the Hungarian revolution, the name of the square changed to Liberty Square. After the Austrian army recaptured the city, the square was renamed Prince Eugene Square. The square is also colloquially referred to as the 'Old City Hall Square''. The building was built in Baroque style between 1731-1734.\n\n   Located in the center of Liberty Square, this statue is the work of two Viennese sculptors, Blim and Wasserburger. On the three sides of the monument are depicted scenes from the last period of the life of St. John Nepomuk. In its center is St. Nepomuk and in the upper part is St. Mary with a crown of stars around her head and holding lily flowers, the symbol of purity.\n\n   The monument belongs to the typology of the plague columns.";
                    break;
                case "The Unirii square":
                    description = "   The Unirii Square is the oldest historical square in Timisoara, decorated in Baroque style.\n\n   Throughout its history the square was also called Hauptplatz (Main Square), Domplatz (Dome Square) and Losonczy Square (after the name of Count Stefan Losonczy, killed in 1552 when the fortress was conquered by the Turks). The name Piața Unirii was given to it in 1919, because the Romanian troops that entered Timișoara stopped here.\n\n    The site is home to important tourist attractions, such as the Roman Catholic Dome, the Baroque Palace, the Serbian Orthodox Cathedral, the Brück House, the Holy Trinity Monument, the mineral water fountain and other architectural monuments. It has a large surface, the dimensions being 150 x 110 m.";
                    break;
                case "The Victory square":
                    description = "   The Victory Square, former Opera Square, is one of the central squares of Timișoara, the place where Timișoara was proclaimed on December 20, 1989 the first free city in Romania. At the opposite poles of the square are the Opera to the north and the Metropolitan Cathedral to the south. From the Opera to the Cathedral the promenade on the right is called 'Corso', and the one on the left is called 'Surrogate'.\n\n   Around the square there are cultural institutions - the Romanian Opera, the National Theater, the Hungarian State Theater, the German State Theater, the Metropolitan Cathedral, the Timiș cinemas, the Capitol and the Studio, the Banat Museum, art galleries and many shops.";
                    break;
                case "The Capitoline Wolf Statue":
                    description = "   The statue the Capitoline Wolf is a statue depicting the legend of the founders of Rome, the brothers Romulus and Remus, breastfed by a wolf. The statue depicts the legend of the founding of Rome, according to which the two brothers who founded the city were cared for by a wolf.\n\n   A true symbol of Latinity, but also of Timisoara, the statue of Lupoaica was placed in Victoriei Square, between the Cathedral and the Opera, in 1926, right on St. George's Day, on April 23.\n\n    Copy of the famous Capitoline Wolf, the Statue of the Wolf, today one of the symbolic statues of the city is a donation made by the municipality of Rome.";
                    break;
                case "The Sokolovac canyon":
                    description = "   Bosman-Sokolovac is 10 km long walking trail, with an average slope of 15%, which classifies it as moderately difficult walking trail.\n\n   This walking trail requires active hiking because trail climbs along the cliffs above the Danube, all the way to the top of Sokolovac on 683 m of altitude. From the top there can be seen gorge Gospođin Vir and the Romanian Nature Park Portile de Fier on the other bank of the Danube.";
                    break;
                case "The Golubac fortress":
                    description = "   The Golubac fortress was a medieval fortified town on the south side of the Danube River, 4 km (2.5 mi) downstream from the modern-day town of Golubac, Serbia. According the recent discoveries, the fortress, which was built during the 14th century by Medieval Serbian state, is split into three compounds which were built in stages. It has ten towers, most of which started square, and several of which received many-sided reinforcements with the advent of firearms. Towers were not connected for easier defense. Also inside the fortress were found Serbian Medieval frescos.\n\n   Golubac Fortress has had a tumultuous history. Prior to its construction it was the site of a Roman settlement. During the Middle Ages, it became the object of many battles, especially between the Ottoman Empire and the Kingdom of Hungary. It changed hands repeatedly, passing between Turks, Bulgarians, Hungarians, Serbs, and Austrians, until 1867, when it was turned over to the Serbian Knez, Mihailo Obrenović III. Now, it is a popular tourist attraction in the region and a sightseeing point on Danube boat tours.\n\n   The fortress has a distinction of successfully repelling over 120 conquering attacks during history.";
                    break;
                case "The Ram fortress":
                    description = "   The Ram Fortress is a 15th century fort situated on a steep slope on the right bank of the Danube, in the village of Ram, municipality of Veliko Gradište, eastern Serbia. The fortress is located on a rock, which is from the northeast side tilted towards the Danube. It is assumed that the city was built on the opposite side from Haram fortress, which was located across the Danube and left no remnants. The remains of the city are in good condition.";
                    break;
                case "The Smederevo fortress":
                    description = "   The Smederevo Fortress is a medieval fortified city in Smederevo, Serbia, which was temporary capital of Serbia in the Middle Ages. It was built between 1427 and 1430 on the order of Despot Đurađ Branković, the ruler of the Serbian Despotate. It was further fortified by the Ottoman Empire, which had taken the city in 1459.\n\n    The fortress withstood several sieges by Ottomans and Serbs, surviving relatively unscathed. During World War II it was heavily damaged, by explosions and bombing. As of 2009 it is in the midst of extensive restoration and conservation work, despite which the fortress remains \"one of the rare preserved courts of medieval Serbian rulers.";
                    break;
                case "The Deliblato Sands":
                    description = "   The Deliblato Sands is a large sand area covering around 300 km2 (120 sq mi) of ground in Vojvodina province, Serbia. It is located in southern Banat, situated between the river Danube and the southwestern slopes of the Carpathian Mountains. The sands are named after the village of Deliblato,[1] in the municipality of Kovin. Its main masses are elliptical shaped hills with steppe grassland plains and steppe forests.\n\n    The Deliblato Sands is the largest sandy terrain in Europe, once part of a vast prehistoric desert, having originated from the withdrawal of the Pannonian Sea. They are home to many endemic species of plants and animals which are rare or endangered in Europe and globally. Due to its forest and surroundings, it was declared a Special Nature Reserve. On a national level, it represents a natural asset of special importance falling under protection category I.\n\n   It is referred to as the 'European Sahara', or the 'Old Continent's oldest desert'.";
                    break;
                case "Tabula Traiana":
                    description = "   Not far from the Statue of Decebalus, on the Serbian shore, at the exit of Cazanele Mici, for almost 2000 years, there is the Roman memorial plaque 'Tabula Traiana', 4 meters long and 1.75 meters high. Tabula Traiana is a monument erected by the opponent of King Decebalus, the Roman emperor Trajan, to mark the march of Roman imperial troops to Dacia and commemorate the Roman Empire's victories over the Dacian kingdom in 105-106 and the completion of Trajan's Roman military road.\n\n   Tabula Traiana records the beginning of Trajan's suspended road on the territory of Dacia (40 km). You can see the remains of Trajan's road that continued along the river, the path started by Emperor Tiberius. In certain parts where they could not make their way directly through the dislocation of the rocks, square holes were dug in the stone, above the water, at equal distances. In them were fixed horizontally strong beams over which a wooden bridge was placed. The holes in the rock where the bridge beams were fixed are still visible today.";
                    break;
                case "The mill":
                    description = "   Suvača in Kikinda is characteristic of the Vojvodina area of the 19th century. It was built in 1899, and the mill stopped working in 1945. It is located in the western part of town, on the corner of Nemanjina and Moravska streets. The plot of land is 728 square metres (7,840 sq ft). Suvača is a mill for grinding grain that uses the work of horses as its driving force. The mill uses one to five pairs of horses. One pair of horses was able to grind up to 100 kilograms (220 lb) of grain per hour. According to tradition, the taste of bread from wheat ground in Suvača was excellent and high quality. In addition to cereals, the mill at Suvača would process pepper and cinnamon.\n\n   Suvača consists of three connected parts: the drive space, the mill space, and the miller's apartment. The drive space is the compartment with a pyramid roof where the device is located that runs the mill stones. Although the entire facility called Suvača, Suvača is essentially the part of the building in which the device is located.";
                    break;
                case "The sculptures":
                    description = "   The Terracotta Museum in Kikinda is also a must stop, once in the area, for any lover of beauty. The impact with the exhibition is overwhelming when you enter the huge hall of the museum, because there are terracotta pieces of all shapes and sizes, older or newer, concrete or abstract shapes, which put your mind to contribute, to penetrate their secrets. An impressive collection, carefully assembled over time and offered to the general public in a wonderful museum space, inaugurated in December 2017.\n\n   Kikinda itself is worthy of discovery through the eyes of the traveler, because it is a space that urges moments of respite and to simply enjoy the charm of the place. A small provincial town with old churches and buildings, which strikingly resembles so many other nearby provincial towns, either in Hungary or in Romania, because the whole area was, for almost a century and a half, part of the Habsburg Empire . There are terracotta pieces, probably made from grass or posted in front of important buildings, probably also part of the huge collection that Kikinda hosts.";
                    break;
                case "Generala Drapsina street":
                    description = "   You wouldn't expect such nature right next to city center, but here it is. Old trees with their tops cover this street filled with old houses and buildings. The shade provides such a nice place for a walk during those hot summer days, and the music from nearby taverns will make this little walk a thing of magic.";
                    break;
                case "The Pančevo city":
                    description = "   Pančevo is a city and the administrative center of the South Banat District in the autonomous province of Vojvodina, Serbia.\n\n    Pančevo is the fourth largest city in Vojvodina by population. According to the 2011 census, a total of 76,203 inhabitants live in the urban area, while the city administrative area of Pančevo has 123,414 inhabitants. In the late 19th and early 20th century many archaeological artifacts of the Stone Age period were found, remains of settlements and places of burial from the times of Bronze Age (Urnfield culture) and Ancient Rome on the urban area. Most of the objects are exhibited at the National Museum of the town. In 1153, the Arabic Muslim geographer Muhammad al-Idrisi described the settlement as an important mercantile place and that is the first historical mentioning of the town. There is no deed or other evidence of founding the city. Today's urban area was administered by the Bulgarian Empire until the begin of the 11th century, then by the Kingdom of Hungary until the 16th century, when it became part of the Ottoman Empire in 1521. During the Ottoman rule, the city was part of the Temeşvar Eyalet and mostly populated by ethnic Serbs.";
                    break;
                case "Pančevo National Museum":
                    description = "   The National Museum was founded in 1923 and it is located in former neoclassical city hall since several decades. The institution has a valuable permanent exhibition and it is one of the most important museums of Vojvodina.";
                    break;
                case "The St. Gerhard Bishop and Martyr Catholic Church":
                    description = "   Vršac could also be called 'The City of the Three Different Churches'. In the old center is St. Gerhard's Catholic Cathedral, built in the Gothic style in the 19th century. This place of worship is named after the martyred bishop Gerhard, son of King Stephen I of Hungary, former bishop of Cenad, killed during the pagan revolt in Budapest.";
                    break;
                case "The Vršac castle":
                    description = "   Vršac Castle, formerly known as 'Vršac Tower' is a medieval fortress near Vršac, Vojvodina, Serbia. Only Donjon tower remained from the entire complex, but in 2009 reconstruction started, to recreate the entire Vršac Castle.\n\n    Vršac Castle was declared a Monument of Culture of Great Importance in 1991, and is protected by the Republic of Serbia.\n\n    There are two theories about the origin of this fortress. According to the Turkish traveler, Evliya Çelebi, the fortress was built by the Serbian despot Đurađ Branković. Historians consider that Branković built the fortress after the fall of Smederevo in 1439.[2] In its construction the fortress had some architectural elements similar to those in the fortress of Smederevo and the fortress around the Manasija monastery.\n\n   The other theory claims that Vršac Castle is a remnant of the medieval fortress known as Erdesumulu (Hungarian: Érdsomlyó or Érsomlyó, Serbian: Erd-Šomljo / Ерд-Шомљо or Šomljo / Шомљо). However, sources for this theory do not identify Erdesumulu with Vršac, but claim that the location of this town and fortress was further to the east, on the Karaš River, in present-day Romanian Banat.";
                    break;
                case "Vršac city center":
                    description = "   An ideal destination to spend a beautiful weekend is the Serbian town of Vršac. In Romanian Vârșeț, in Hungarian Versec, in German Werschetz or Hennemannstadt, this city is located about 80 kilometers from Timișoara.\n\n   With a population of about 40,000, it is the eighth largest city in Vojvodina and the fourth in the Serbian Banat, one of Serbia's neighboring provinces. There is historical evidence and artifacts that attest that this area was inhabited since the Neolithic, but the first documentary evidence is from the fifteenth century. During the Habsburg Empire, due to mass colonization, almost half of the population was made up of German citizens. Until the Treaty of Trianon, Vršac was part of Timiș County.";
                    break;
                case "The Romanian Orthodox Cathedral":
                    description = "   A place of worship in the old part of the city is the Romanian Orthodox Cathedral, built in 1913 (dedicated to the Ascension of the Lord). The metal gate at the entrance has as ornament two vine leaves and a grape, a sign that we are of course in an important wine-growing area.";
                    break;
                case "The Cathedral of St. John of Nepomuk":
                    description = "   The Cathedral of Saint John of Nepomuk is a Roman Catholic Cathedral in Zrenjanin, Serbia. It is the seat of the Roman Catholic Diocese of Zrenjanin that covers the territory of Serbian Banat. The Cathedral is located in the Zrenjanin's main square, Trg slobode (Freedom Square). It is dedicated to Saint John of Nepomuk.\n\n   For the duration of the Ottoman rule (1552–1718) there stood a mosque, but was razed down by the Austrians following Turkish withdrawal from the city and Banat. However, this is not the first cathedral built following the removal of the mosque. Prior to the cathedral seen today, a Baroque-style church, built in 1768, stood in its place. Over the next century, the building deteriorated badly and the authorities decided to build a new one. The construction of the present-day cathedral commenced in 1864 by the project of Franz Xaver Brandeisz, who also built several churches in Banat, and lasted four years.\n\n   The Zrenjanin Cathedral was built in the Neoclassical style. The interior was decorated by Josef Goigner from Tyrol and the cathedral features a pipe organ made in Timișoara, in 1907. Windows are decorated with stained glass.";
                    break;
                case "Zrenjanin city center":
                    description = "   The Zrenjanin City Hallis located at the Trg Slobode (Liberty Square) in Zrenjanin, Serbia. It is a seat of the Zrenjanin municipality.\n\n   Present-day Zrenjanin (formerly known as Veliki Bečkerek / Nagybecskerek / Großbetschkerek / Becicherecul Mare) was a seat of Torontaliensis county from 1779. A great fire in 1807 destroyed almost every building in the city, including old county building. Construction works for a new building started in 1816 and were finished in 1820 under project of architect Joseph Fischer. After 70 years, county building was re-constructed under projects of two renowned architects from Budapest, Gyula Pártos and Ödön Lechner.\n\n   The county building was added by right and left wings, modernised facade in Neobaroque, new balcony, Zsolnay roof tile patterns and several other things like electrical lightning and telephone line. At that time, it was the most modern building in southern part of the Kingdom of Hungary.";
                    break;
                case "The Court House":
                    description = "   Zrenjanin Court House, also known as Palace of Justice, is a seat of Municipal, District and Trade Court in Zrenjanin.\n\n   The monumental Neromantical building of the District Court dates from the beginning of the 20th century. Construction works started in 1906 and were finished in 1908. It has a dominant long facade along with the Begej river bank, cupolas at the corners of the building. The central risalit at the same time represents the most thoroughly modelled part of the building.\n\n   The building was built according to the projects of two architects from Budapest, who won at the contest - Sándor Eigner and Marcus Rehmer.";
                    break;
                case "The Zrenjanin lake":
                    description = "   The name BEGEJ appeared as early as by the end of the 12th century in the works of Anonymous (a nameless historian of King Bela III), who, writing about the conquering of the state of the Bulgarian-Slavic ruler Glad by the Hungarians, mentioned this name as well. The historians Teodor Orthmayr and Jene Szentklaray stated that the settlement of Becskerek was hiding under the name of 'Begej' (Beguey). However, Felix Milleker, in the history of the town of Veliki-Big Becskerek, stated that the name implied the River Begej, that the word is of Slavic origin and means: to go, to hurry, to flow (beg, begati, bega).\n\n   The River Begej rises in the Carpathian region in Romania and flows through Banat as the left tributary of the River Tisza. It is formed by confluence of three smaller river watercourses - Beregso, Njarad, and Jer. It flows into the River Tisza nearby the settlement Perlez. The river is 254 km long, out of which 76 km in Serbia. From Timisoara to Zrenjanin, and further on to the river mouth, it has been transformed in the navigable, the so-called Begej Canal. The old Begej Canal, the canalized river bed, is 97 km long, and the new one 83 km (up to Timisoara). The main port of the navigable Begej River is in the City of Zrenjanin. The River flows through Zrenjanin along the length of its course of around 13 kilometers.";
                    break;
                case "The Bukovac Palace":
                    description = "   The Bukovac palace is a building located at the beginning of King Alexander I street, in Zrenjanin.\n\n   The palace was built in 1895 by an unknown architect, in the manner of Neo-Renaissance. It has two floors and a balcony towards the main square. Windows are made to look like biphoras. The palace was built by a trader Stevan Bukovac.\n\n   In the 1960s, Bukovac palace was cut off from the rest of the 19th century buildings by raising a compartment building just behind it. Another building was built in 1998 to fill in the space between Bukovac palace and the soc-realist building.";
                    break;
                case "The Finance Palace":
                    description = "   The Finance palace is a two-floored neo-renaissance palace on the main square in Zrenjanin, Serbia, and one of the most beautiful buildings in the city. The National Museum of Zrenjanin moved into it in 1966 and it is located next to the theatre building.\n\n    City authorities chosen project for the building made by Hungarian architect István Kiss. Construction works started in 1893 and were finished in 1894. By his first choice, architect chosen facade towards Begej to be building's main facade. However, he later changed plan and choose square facade to be the most impressive facade of the building. The most remarkable detail of this building are, there is no doubt, four statues on its main facade, depicting 'Industry', 'Agriculture', 'Science' and 'Merchantry'. Main facade also has a balcony on the first floor. The building has shops at the ground floor and an exhibition gallery.";
                    break;
                case "The theatre":
                    description = "   The theatre building  was built in 1839 from the old wheat warehouse. It is located at the city main square - Trg slobode (Liberty Square). It is located between buildings of the Old Vojvodina hotel and Finance palace.\n\n   In the eighteenth century, Spanish who were settled in Bečkerek at that time, tore down the last remains of the Bečkerek fortress and built a wheat warehouse. A whole century later, the building has been bought out by town authorities, who redesigned its interior as a theater. Serbian National Theatre from Novi Sad performed in this building as a travelling crew, few years after founding in 1861.";
                    break;
            }
            if (!description.isEmpty())
                location_description.setText(description);
        }
    }
}